trainer:
  max_epochs: 24
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "eomt"
      name: "finetune_coco_to_cityscapes"
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./checkpoints/finetuned"
        filename: "eomt-cityscapes-{epoch:02d}-{metrics/val_iou_all:.4f}"
        monitor: "metrics/val_iou_all"   # ← era "val/miou"
        mode: "max"
        save_top_k: 3
        save_last: true
        every_n_epochs: 1
model:
  class_path: finetuning_lightning_module.FinetuneLightningModule
  init_args:
    mode: "last_n_blocks"
    num_classes: 19
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [5920, 14836, 23752]  # start_steps=[16.6%, 41.6%, 66.6%] 
    attn_mask_annealing_end_steps: [11876, 20792, 29708]   # end_steps=[33.3%, 58.3%, 83.3%]
    # These percentages represents a ratio found in the configs for EoMT on Cityscapes and EoMT on COCO. By computing the ratio between the start/end steps and the 
    # total steps, we found out that in both configs the ratio was constant. So we decided to reutilize it during the fine tuning.
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 200
        num_blocks: 3
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: vit_base_patch14_reg4_dinov2

data:
  class_path: datasets.cityscapes_semantic.CityscapesSemantic
  init_args:
    batch_size: 2
    img_size: [640,640]
